package testUtility;

import static org.junit.Assert.assertTrue;

import java.io.PrintStream;
import java.sql.SQLException;
import java.text.ParseException;

import org.junit.Before;
import org.junit.Test;

import model.dao.CategoriaDao;
import model.dao.DisponibilitaDao;
import model.dao.FormatoreDao;
import model.dao.InteresseDao;
import model.dao.InteresseStudenteDao;
import model.dao.IscrizioneDao;
import model.dao.PercorsoFormativoDao;
import model.dao.PreferenzaStudenteDao;
import model.dao.StudenteDao;
import model.entity.CategoriaEntity;
import model.entity.DisponibilitaEntity;
import model.entity.FormatoreEntity;
import model.entity.InteresseEntity;
import model.entity.InteresseStudenteEntity;
import model.entity.IscrizioneEntity;
import model.entity.PercorsoFormativoEntity;
import model.entity.PreferenzaStudenteEntity;
import model.entity.StudenteEntity;
import model.utils.Utils;

public class InserimentiTest {
	
	FormatoreDao fDao;
	StudenteDao sDao;
	PercorsoFormativoDao pfDao;
	CategoriaDao cDao;
	DisponibilitaDao dDao;
	PreferenzaStudenteDao psDao;
	InteresseDao interesseDao;
	InteresseStudenteDao isDao;
	IscrizioneDao iscrizioneDao;
	
	PercorsoFormativoEntity pf0,   pf1,   pf2,   pf3,   pf4,   pf5,   pf6,   pf7,   pf8,   pf9;
	PercorsoFormativoEntity pf10,  pf11,  pf12,  pf13,  pf14,  pf15,  pf16,  pf17,  pf18,  pf19;
	PercorsoFormativoEntity pf20,  pf21,  pf22,  pf23,  pf24,  pf25,  pf26,  pf27,  pf28,  pf29;
	PercorsoFormativoEntity pf30;
	
	void setupNaming() {
		
		System.setProperty("java.naming.factory.initial","testUtility.MyContextFactory");
		
	}
	
	@Before
	public void setUp() {
		
		setupNaming();
		
		fDao = new FormatoreDao();
		sDao = new StudenteDao();
		pfDao = new PercorsoFormativoDao();
		cDao = new CategoriaDao();
		dDao = new DisponibilitaDao();
		psDao = new PreferenzaStudenteDao();
		interesseDao = new InteresseDao();
		isDao = new InteresseStudenteDao();
		iscrizioneDao = new IscrizioneDao();
		
	}
	
	@Test
	public void testInserimenti() throws SQLException, ParseException {
		
		this.testInserimentoFormatori();
		this.testInserimentoStudenti();
		this.testInserimentoCategorie();
		this.testInserimentoPercorsi();
		this.testInserimentoDisponibilita();
		this.testInserimentoPreferenzaStudente();
		this.testInserimentoInteressi();
		this.testInserimentoInteressiStudenti();
		this.testInserimentoIscrizioni();
		
	}
	
	public void testInserimentoFormatori() throws SQLException, ParseException {
		
		FormatoreEntity f0 = new FormatoreEntity();
		f0.setEmail("mrossi@gmail.com");
		f0.setPassword("mariorossi");
		f0.setName("Mario");
		f0.setSurname("Rossi");
		f0.setGender("m");
		f0.setBirthDate(Utils.toDate("10-05-1980"));
		f0.setCodiceFiscale("abcabc");
		f0.setContoCorrente("defdef");
		
		FormatoreEntity f1 = new FormatoreEntity();
		f1.setEmail("testFormatore@gmail.it");
		f1.setPassword("cambioPassword");
		f1.setName("Test nome");
		f1.setSurname("test cognome");
		f1.setGender("f");
		f1.setBirthDate(Utils.toDate("22-10-1980"));
		f1.setCodiceFiscale("sdasdasd");
		f1.setContoCorrente("ITSDASDA5411DASD5415");
			
		fDao.doSave(f0);
		fDao.doSave(f1);
		
	}
	
	public void testInserimentoStudenti() throws SQLException, ParseException {
		
		StudenteEntity s0 = new StudenteEntity();
		s0.setEmail("studente@gmail.com");
		s0.setPassword("studente");
		s0.setName("Matteo");
		s0.setSurname("Gialli");
		s0.setGender("m");
		s0.setBirthDate(Utils.toDate("05-10-1995"));
		
		sDao.doSave(s0);
		
	}
	
	public void testInserimentoCategorie() throws SQLException {
		
		CategoriaEntity categoria0 = new CategoriaEntity();
		categoria0.setNome("Matematica");
		categoria0.setDescrizione("Tutti i percorsi formativi che trattano argomenti matematici");
		categoria0.setAmbito("Attività formative integrative/affini");
		CategoriaEntity categoria1 = new CategoriaEntity();		
		categoria1.setNome("Informatica");
		categoria1.setDescrizione("Tutti i percorsi formativi che trattano argomenti informatici");
		categoria1.setAmbito("Discipline informatiche");
		CategoriaEntity categoria2 = new CategoriaEntity();
		categoria2.setNome("Linguaggi");
		categoria2.setDescrizione("Tutti i percorsi formativi che trattano 1 o più linguagi");
		categoria2.setAmbito("Discipline informatiche");
		CategoriaEntity categoria3 = new CategoriaEntity();
		categoria3.setNome("Linguaggi di programmazione");
		categoria3.setDescrizione("Tutti i percorsi formativi che trattano 1 o più linguaggi di programmazione");
		categoria3.setAmbito("Discipline informatiche");
		CategoriaEntity categoria4 = new CategoriaEntity();
		categoria4.setNome("Linguaggi di markup");
		categoria4.setDescrizione("Tutti i percorsi formativi che trattano 1 o più linguaggi di markup");
		categoria4.setAmbito("Discipline informatiche");
		CategoriaEntity categoria5 = new CategoriaEntity();
		categoria5.setNome("Linguaggi di scripting");
		categoria5.setDescrizione("Tutti i percorsi formativi che trattano 1 o più linguaggi di scripting");
		categoria5.setAmbito("Discipline informatiche");
		CategoriaEntity categoria6 = new CategoriaEntity();
		categoria6.setNome("Linguaggi di modellazione");
		categoria6.setDescrizione("Tutti i percorsi formativi che trattano 1 o più linguaggi di modellazione");
		categoria6.setAmbito("Discipline informatiche");
		
		
		cDao.doSave(categoria0);
		cDao.doSave(categoria1);
		cDao.doSave(categoria2);
		cDao.doSave(categoria3);
		cDao.doSave(categoria4);
		cDao.doSave(categoria5);
		cDao.doSave(categoria6);
		
	}
	
	public void testInserimentoPercorsi() throws SQLException {
		
		pf0 = new PercorsoFormativoEntity(); pf1 = new PercorsoFormativoEntity(); pf2 = new PercorsoFormativoEntity();
		pf3 = new PercorsoFormativoEntity(); pf4 = new PercorsoFormativoEntity(); pf5 = new PercorsoFormativoEntity();
		pf6 = new PercorsoFormativoEntity(); pf7 = new PercorsoFormativoEntity(); pf8 = new PercorsoFormativoEntity();
		pf9 = new PercorsoFormativoEntity(); pf10 = new PercorsoFormativoEntity(); pf11 = new PercorsoFormativoEntity();
		pf12 = new PercorsoFormativoEntity(); pf13 = new PercorsoFormativoEntity(); pf14 = new PercorsoFormativoEntity();
		pf15 = new PercorsoFormativoEntity(); pf16 = new PercorsoFormativoEntity(); pf17 = new PercorsoFormativoEntity();
		pf18 = new PercorsoFormativoEntity(); pf19 = new PercorsoFormativoEntity(); pf20 = new PercorsoFormativoEntity();
		pf21 = new PercorsoFormativoEntity(); pf22 = new PercorsoFormativoEntity(); pf23 = new PercorsoFormativoEntity();
		pf24 = new PercorsoFormativoEntity(); pf25 = new PercorsoFormativoEntity(); pf26 = new PercorsoFormativoEntity();
		pf27 = new PercorsoFormativoEntity(); pf28 = new PercorsoFormativoEntity(); pf29 = new PercorsoFormativoEntity();
		pf30 = new PercorsoFormativoEntity();
		
		pf0.setNome("Tecnologie Software per il Web");
		pf1.setNome ("Architettura degli elaboratori");
		pf2.setNome ("Calcolo delle probabilità e statistica matematica");
		pf3.setNome ("Programmazione e strutture dati");
		pf4.setNome ("Programmazione Object Oriented");
		pf5.setNome ("Grafica ed iterattività");
		pf6.setNome ("Elementi di teoria della computazione");
		pf7.setNome ("Sicurezza");
		pf8.setNome ("Basi di Dati 1");
		pf9.setNome ("Fondamenti di visione artificiale e biometrica");
		pf10.setNome ("Analisi matematica 1");
		pf11.setNome ("Fondamenti di intelligenza artificiale");
		pf12.setNome ("Programmazione 1");
		pf13.setNome ("Programmazione avanzata");
		pf14.setNome ("Interazione uomo macchina");
		pf15.setNome ("Ricerca operativa");
		pf16.setNome ("HTML 5 da zero");
		pf17.setNome ("Basi di dati 2");
		pf18.setNome ("Cybersecurity");
		pf19.setNome ("Gestione dei progetti software");
		pf20.setNome("Analisi Matematica 2");
		pf21.setNome("Basi di Dati 1");
		pf22.setNome("Intelligenza artificiale");
		pf23.setNome("Programmazione avanzata");
		pf24.setNome("Robot programming");
		pf25.setNome("Introduzione al linguaggio c++");
		pf26.setNome("Algebra lineare");
		pf27.setNome("Geometria analitica");
		pf28.setNome("Matematica discreta");
		pf29.setNome("Go - Dalle Basi ai Concetti Avanzat");
		pf30.setNome("Concorrenza in Go (Golang)");
		
		pf0.setIndice_contenuti("L’INSEGNAMENTO APPROFONDISCE LA PROGRAMMAZIONE LATO CLIENT (HTML, CSS, JAVASCRIPT, JQUERY), LA PROGRAMMAZIONE LATO SERVER (JSP, SERVLET) E STRUMENTI E MODELLI PER LO SCAMBIO DI DATI (JDOM, XML, AJAX, JSON).IN PARTICOLARE, SONO TRATTATI I SEGUENTI ARGOMENTI: •NOZIONI URI, PROTOCOLLO HTTP, ARCHITETTURE CLIENT-SERVER •ISTALLAZIONE DI APPLICAZIONI WEB SU TOMCAT •LINGUAGGI HTML 5 E CSS 3 (RESPONSIVE CSS) •DESCRIZIONE DELLE INFORMAZIONI: XML (JDOM, DTD, PARSER DOM E SAX) E JSON •SESSIONI E GESTIONE DELLO STATO •IL DESIGN PATTERN MODEL-VIEW-CONTROLLER (MVC) •PROGRAMMAZIONE LATO SERVER: SERVLET, JSP, EL, JAVABEAN •SICUREZZA ED APPLICAZIONI WEB •PROGRAMMAZIONE LATO CLIENT: JAVASCRIPT (AJAX, JQUERY)");
		pf1.setIndice_contenuti ("1) ARCHITETTURA DEI CALCOLATORI– COSA E? UN CALCOLATORE – TIPI DI CALCOLATORI – COMPONENTI DI UN CALCOLATORE - ESECUZIONE DI UN PROGRAMMA (1 CREDITO)\r\n"
				+ "<br>2) RAPPRESENTAZIONE DELL'INFORMAZIONE - RAPPRESENTAZIONE DEGLI INTERI PER ALGORITMI DI CONVERSIONE PER INTERI (DEC-BIN, BIN-DEC)) - RAPPRESENTAZIONE E ARITMETICA IN COMPLEMENTO A DUE - RAPPRESENTAZIONE IN VIRGOLA MOBILE - CODIFICA ASCII (PP. 120-122) (1 CREDITO)\r\n"
				+ "<br>3) LOGICA DIGITALE - ALGEBRA BOOLEANA - RETI COMBINATORIE E ALU - ELEMENTI DI MEMORIZZAZIONE: FLIP-FLOP (1 CREDITO)\r\n"
				+ "<br>4) LINGUAGGIO ASSEMBLER DI UNA MACCHINA RISC (2 CREDITI)\r\n"
				+ "<br>5) IMPLEMENTAZIONE DELLA UNITÀ DI ELABORAZIONE A CICLO SINGOLO (1 CREDITO)\r\n"
				+ "<br>6) MISURA DELLE PRESTAZIONI, MIGLIORAMENTO DELLE PRESTAZIONI MEDIANTE PIPELINE (2 CREDITI)\r\n"
				+ "<br>7) GERARCHIE DI MEMORIA (1 CREDITO)\r\n"
				+ "<br>8) REGISTER FILE E MODULI COMBINATORI (1 CREDITO)");
		pf2.setIndice_contenuti ("ESPERIMENTI ALEATORI. SPAZIO CAMPIONARIO. PROBABILITÀ. SPAZIO DI PROBABILITÀ. "
				+ "PROBABILITÀ CONDIZIONATA. INDIPENDENZA. ELEMENTI DI CALCOLO COMBINATORIO. VARIABILE ALEATORIA. "
				+ "FUNZIONE DI DISTRIBUZIONE. MEDIA, DEVIAZIONE STANDARD E VARIANZA. "
				+ "PRINCIPALI VARIABILI ALEATORIE DISCRETE E CONTINUE. VARIABILI ALEATORIE DOPPIE DISCRETE. "
				+ "FUNZIONI DI PROBABILITÀ MARGINALI. FUNZIONI DI PROBABILITÀ CONDIZIONATE. INDIPENDENZA. "
				+ "COVARIANZA E CORRELAZIONE. VARIABILI ALEATORIE MULTIPLE. MOMENTI. DISUGUAGLIANZA DI MARKOV E CHEBYSHEV. "
				+ "LEGGE DEI GRANDI NUMERI. TEOREMA DI BERNOULLI. TEOREMA DEL LIMITE CENTRALE. CAMPIONAMENTO. "
				+ "POPOLAZIONE E CAMPIONE. INFERENZA STATISTICA. STIMA DEI PARAMETRI. STATISTICHE CAMPIONARIE. "
				+ "MEDIA E VARIANZA CAMPIONARIE. DISTRIBUZIONE CAMPIONARIA DELLA MEDIA. "
				+ "ORGANIZZAZIONE E DESCRIZIONE DEI DATI. TABELLE. GRAFICI DI FREQUENZE. ISTOGRAMMI. PERCENTILI CAMPIONARI. "
				+ "DATI BIVARIATI. COEFFICIENTE DI CORRELAZIONE CAMPIONARIO.");
		pf3.setIndice_contenuti ("1.COMPLEMENTI DI PROGRAMMAZIONE IN C: STRUTTURE AUTO-REFERENZIATE, STRUTTURE DINAMICHE (LISTE, ALBERI)\r\n"
				+ "2.NOZIONI GENERALI SUI MODELLI DI MEMORIA, MEMORIA STATICA E MEMORIA DINAMICA, STACK E RECORD DI ATTIVAZIONE, NOMI ED AMBIENTE, REGOLE DI SCOPE STATICO E DINAMICO\r\n"
				+ "3.PUNTATORI E ALLOCAZIONE DINAMICA DELLA MEMORIA\r\n"
				+ "4.ASTRAZIONI E MODULI: TIPI DI ASTRAZIONE, INTERFACCIA E IMPLEMENTAZIONE DI UN MODULO, REALIZZAZIONE DI MODULI IN C\r\n"
				+ "5.RICORSIONE: ASPETTI E DEFINIZIONI GENERALI, RICORSIONE E ITERAZIONE, GESTIONE DELL’ESECUZIONE DI PROGRAMMI RICORSIVI\r\n"
				+ "6.ALGORITMI ITERATIVI E RICORSIVI SU ARRAY, ALGORITMI DI ORDINAMENTO.\r\n"
				+ "7.CENNI SU COMPLESSITÀ COMPUTAZIONALE\r\n"
				+ "8.TIPI DI DATI ASTRATTI (ADT): SPECIFICA SINTATTICA E SEMANTICA, PROGETTO E REALIZZAZIONE.\r\n"
				+ "9.LISTE: ASPETTI GENERALI, VARIANTI E SPECIFICA DEGLI ADT, DEFINIZIONE DELLA STRUTTURA DATI E IMPLEMENTAZIONI ALTERNATIVE BASATE SU ARRAY E STRUTTURE A PUNTATORI, SPECIFICA E REALIZZAZIONE DEGLI OPERATORI (VERSIONI ITERATIVE E RICORSIVE), ALGORITMI SU LISTE ED APPLICAZIONI.\r\n"
				+ "10.PILE E CODE: SPECIFICA DEGLI ADT, OPERATORI DI PILA E CODA, IMPLEMENTAZIONI ALTERNATIVE DELLE STRUTTURE DATI, APPLICAZIONI DI PILE E CODE.\r\n"
				+ "11.ALBERI E ALBERI BINARI: ASPETTI GENERALI, SPECIFICA DEGLI ADT, DEFINIZIONE DELLA STRUTTURA DATI E OPERATORI DI BASE, ALGORITMI DI VISITA E ALTRI ALGORITMI SUGLI ALBERI (IN VERSIONE ITERATIVA E RICORSIVA), APPLICAZIONI DI ALBERI E ALBERI BINARI.\r\n"
				+ "12.INSIEMI ORDINATI E ALBERI DI RICERCA BINARIA: SPECIFICA E IMPLEMENTAZIONE DELL’ADT, OPERATORI DI CREAZIONE, INSERIMENTO, CANCELLAZIONE E RICERCA, ALGORITMI DI VISITA, CENNI SUL BILANCIAMENTO DEGLI ALBERI DI RICERCA BINARIA, APPLICAZIONI DI ALBERI DI RICERCA BINARIA.\r\n"
				+ "13.CENNI SU CODE A PRIORITÀ E HEAP\r\n"
				+ "14.INSIEMI, TABELLE E TABELLE HASH: ASPETTI GENERALI, SPECIFICA E IMPLEMENTAZIONE DELL’ADT, FUNZIONI DI HASHING, OPERATORI DI CREAZIONE, INSERIMENTO, CANCELLAZIONE E RICERCA, GESTIONE DELLE COLLISIONI CON LISTA CONCATENATA ED INDIRIZZAMENTO APERTO, APPLICAZIONI DI TABELLE HASH.");
		pf4.setIndice_contenuti ("DOPO UNA INTRODUZIONE ALLA PROGRAMMAZIONE ORIENTATA AGLI OGGETTI, EVIDENZIANDO ANCHE LE DIFFERENZE PRINCIPALI CON ALTRI APPROCCI (PER ESEMPIO QUELLO PROCEDURALE), IL CORSO SI CONCENTRERÀ SUI SEGUENTI ARGOMENTI:\r\n"
				+ "•LA PROGRAMMAZIONE ORIENTATA AGLI OGGETTI E CONCETTI DI ASTRAZIONE DEI DATI E DI INCAPSULAMENTO\r\n"
				+ "•INTRODUZIONE A JAVA E AL PROCESSO DI COMPILAZIONE\r\n"
				+ "•INTRODUZIONE AL TOOLKIT DI PROGRAMMAZIONE JDK 8.0\r\n"
				+ "•OGGETTI, VARIABILI, RIFERIMENTI; CLASSI E METODI, COMUNICAZIONE FRA OGGETTI, PARAMETRI ESPLICITI E IMPLICITI; IL RIFERIMENTO THIS\r\n"
				+ "•TIPI DI DATI FONDAMENTALI. ARITMETICA E FUNZIONI MATEMATICHE\r\n"
				+ "•INVOCAZIONE DI METODI STATICI\r\n"
				+ "•LA CLASSE STRING\r\n"
				+ "•FILE E FLUSSI. LEGGERE E SCRIVERE FILE DI TESTO; FORMATO BINARIO E FORMATO DI TESTO\r\n"
				+ "•RICHIAMI SUI COSTRUTTI DI CONTROLLO\r\n"
				+ "•LE COLLEZIONI IN JAVA \r\n"
				+ "•CENNI SUI TIPI GENERICI, SUI TIPI ENUMERATIVI E SUI MECCANISMI DI ‘AUTOBOXING’ E ‘UNBOXING’. FOR GENERICO (FOR EACH)\r\n"
				+ "•PROGETTAZIONE DI CLASSI. CONCETTI DI COESIONE E ACCOPPIAMENTO\r\n"
				+ "•INTERFACCE E POLIMORFISMO\r\n"
				+ "•EREDITARIETÀ E RIUSO\r\n"
				+ "•MECCANISMO DI GESTIONE DELLE ECCEZIONI\r\n"
				+ "•TESTING: VERIFICA DEL COMPORTAMENTO DEGLI OGGETTI; SCELTA DEI CASI DI TEST; INTEGRAZIONE DI CLASSI. DEBUGGING\r\n"
				+ "•ESPRESSIONI LAMBDA PER LA DEFINIZIONE DI FUNZIONI ANONIME\r\n"
				+ "•PROGRAMMAZIONE GRAFICA\r\n"
				+ "•PROGRAMMARE AD EVENTI");
		pf5.setIndice_contenuti ("INTRODUZIONE ALLA COMPUTER GRAFICA 3D\r\n"
				+ "FONDAMENTI DI COMPUTER GRAFICA (SPAZIO 3D, PRIMITIVE GEOMETRICHE, TRASFORMAZIONI)\r\n"
				+ "MODELLAZIONE SUPERFICIALE (MODELLAZIONE POLIGONALE, SUPERFICI PARAMETRICHE, SUPERFICI DI SUDDIVISIONE, ETC.)\r\n"
				+ "EQUAZIONE DELLA RADIANZA\r\n"
				+ "LOCAL ILLUMINATION E RAY TRACING\r\n"
				+ "CONCETTO DI CAMERA\r\n"
				+ "CENNI SULLA PERCEZIONE\r\n"
				+ "STEREOSCOPIA\r\n"
				+ "INTERAZIONE APTICA\r\n"
				+ "MOTION CAPTURE\r\n"
				+ "REALTÀ AUMENTATA\r\n"
				+ "DISPOSITIVI DI INPUT, OUTPUT,\r\n"
				+ "MOTORI 3D E UNITY: INTRODUZIONE AI MOTORI 3D E UNITY\r\n"
				+ "CARATTERISTICHE PRINCIPALI DI UNITY"
				+ "UTILIZZO DI C# PER GLI SCRIPTING");
		pf6.setIndice_contenuti ("MODELLI DI COMPUTAZIONE: AUTOMI FINITI DETERMINISTICI E NON DETERMINISTICI. ESPRESSIONI REGOLARI. PROPRIETÀ DI CHIUSURA DEI LINGUAGGI REGOLARI. TEOREMA DI KLEENE. PUMPING LEMMA PER I LINGUAGGI REGOLARI. MACCHINA DI TURING DETERMINISTICA A NASTRO SINGOLO. IL LINGUAGGIO RICONOSCIUTO DA UNA MACCHINA DI TURING. VARIANTI DI MACCHINE DI TURING E LORO EQUIVALENZA.\r\n"
				+ "\r\n"
				+ "IL CONCETTO DI COMPUTABILITÀ: FUNZIONI CALCOLABILI, LINGUAGGI DECIDIBILI E LINGUAGGI TURING RICONOSCIBILI. LINGUAGGI DECIDIBILI E LINGUAGGI INDECIDIBILI. IL PROBLEMA DELLA FERMATA. RIDUZIONI, TEOREMA DI RICE.\r\n"
				+ "\r\n"
				+ "IL CONCETTO DI COMPLESSITÀ: MISURE DI COMPLESSITÀ: COMPLESSITÀ IN TEMPO DETERMINISTICO E NON DETERMINISTICO. RELAZIONI DI COMPLESSITÀ TRA VARIANTI DI MACCHINE DI TURING. LA CLASSE P. LA CLASSE NP. RIDUCIBILITÀ IN TEMPO POLINOMIALE. DEFINIZIONE DI NP-COMPLETEZZA. RIDUZIONI POLINOMIALI. ESEMPI DI LINGUAGGI NP-COMPLETI.");
		pf7.setIndice_contenuti ("1. STRUMENTI CRITTOGRAFICI\r\n"
				+ "2. INFRASTRUTTURE DI SICUREZZA\r\n"
				+ "3. SICUREZZA DEI SISTEMI E DELLE RETI\r\n"
				+ "4. LEGISLAZIONE, STANDARD E SICUREZZA");
		pf8.setIndice_contenuti ("MODELLI AVANZATI E TECNOLOGIE DI BASI DI DATI UTILIZZATE NEL CONTESTO DEI SISTEMI INFORMATIVI AZIENDALI:\r\n"
				+ "•ORGANIZZAZIONE FISICA DEI DATI ED INDICIZZAZIONE\r\n"
				+ "•CONCORRENZA\r\n"
				+ "•GESTIONE DELLE TRANSAZIONI\r\n"
				+ "•BASI DI DATI DISTRIBUITE\r\n"
				+ "•ASPETTI DI PRIVACY E CONTROLLO DELL’ACCESSO\r\n"
				+ "\r\n"
				+ "TEMATICHE INERENTI ASPETTI EVOLUTI DI GESTIONE DEI DATI:\r\n"
				+ "•DATABASE SEMI STRUTTURATI\r\n"
				+ "•INFORMATION RETRIEVAL\r\n"
				+ "•DATA WAREHOUSE\r\n"
				+ "•SISTEMI DI BUSINESS INTELLIGENCE\r\n"
				+ "•BASI DI DATI XML E MULTIMEDIALI\r\n"
				+ "•BIG DATA E NOSQL");
		pf9.setIndice_contenuti ("1.PSICOLOGIA DELLA PERCEZIONE (CENNI) (2H FRONTALI)\r\n"
				+ "2.DIGITAL FORENSICS (3H FRONTALI)\r\n"
				+ "3.TECNICHE AVANZATE DI COMPUTER VISION E TRASFORMATE (OPERATORI, LOCALI, FOURIER, WAVELET, COSENO)\r\n"
				+ "4.BIOMETRIA (2D E 3D)\r\n"
				+ "5.SISTEMI MULTIBIOMETRICI\r\n"
				+ "6.ANALISI DELLE PRESTAZIONI\r\n"
				+ "7.ANALISI MULTIMEDIALE FORENSE: IMMAGINI E VIDEO\r\n"
				+ "8.TECNICHE INVESTIGATIVE MEDIANTE BIOMETRIE\r\n"
				+ "9.IMPLICAZIONI LEGALI ED ETICHE (CENNI)");
		pf10.setIndice_contenuti("I NUMERI REALI\r\n"
				+ "ASSIOMI DEI NUMERI REALI E CONSEGUENZE. NUMERI NATURALI, INTERI E RAZIONALI. INSIEMI NUMERICI: INSIEME LIMITATO, MASSIMO E MINIMO, ESTREMO INFERIORE E SUPERIORE. UNICITÀ DEL MINIMO (DIM). TH DI ESISTENZA DELL'ESTREMO SUPERIORE (DIM). INSIEMI NON LIMITATI. INTERVALLI. PROPRIETÀ DI ARCHIMEDE (DIM). NON COMPLETEZZA DELL'INSIEME DEI NUMERI RAZIONALI (DIM).\r\n"
				+ "\r\n"
				+ "FUNZIONI REALI DI UNA VARIABILE REALE\r\n"
				+ "DEFINIZIONE E NOTAZIONI. ESTREMI. RAPPRESENTAZIONE CARTESIANA. FUNZIONI PARI, FUNZIONI DISPARI E FUNZIONI PERIODICHE. ALGEBRA DELLE FUNZIONI. COMPOSIZIONE DI FUNZIONI. FUNZIONI INVERTIBILI. FUNZIONI MONOTONE. INVERTIBILITÀ DELLE FUNZIONI MONOTONE(DIM).\r\n"
				+ "\r\n"
				+ "FUNZIONI ELEMENTARI\r\n"
				+ "FUNZIONE LINEARE. FUNZIONE VALORE ASSOLUTO. DISUGUAGLIANZA TRIANGOLARE. FUNZIONI POTENZA. FUNZIONE ESPONENZIALE. FUNZIONE LOGARITMO. FUNZIONI TRIGONOMETRICHE E TRIGONOMETRICHE INVERSE.\r\n"
				+ "\r\n"
				+ "SUCCESSIONI NUMERICHE\r\n"
				+ "DEFINIZIONE E NOTAZIONI. RAPPRESENTAZIONE GRAFICA DI UNA SUCCESSIONE. SUCCESSIONI CONVERGENTI: DEFINIZIONE ED ESEMPI. TH SULL'UNICITÀ DEL LIMITE (DIM). SUCCESSIONI DIVERGENTI: DEFINIZIONI ED ESEMPI. VERIFICHE DI LIMITI. SUCCESSIONI NON REGOLARI. SUCCESSIONI LIMITATE. LIMITATEZZA DELLE SUCCESSIONI CONVERGENTI(DIM). OPERAZIONI CON I LIMITI DI SUCCESSIONI (DIMOSTRAZIONE DELLA SOMMA E DEL PRODOTTO SOLO NEL CASO DELLA CONVERGENZA). FORME INDETERMINATE. TH DELLA PERMANENZA DEL SEGNO E COROLLARI(DIM). TH DEI CARABINIERI (DIM). TH DEL PRODOTTO DI UNA SUCCESSIONE LIMITATA PER UNA INFINITESIMA. SUCCESSIONI MONOTONE E RELATIVO TH (DIM). IL NUMERO E. ALCUNI LIMITI NOTEVOLI. CRITERIO DEL RAPPORTO E SUE APPLICAZIONI. INFINITI DI ORDINE CRESCENTE. SUCCESSIONI ESTRATTE. TH DI BOLZANO-WEIERSTRASS.\r\n"
				+ "LIMITI DI FUNZIONI\r\n"
				+ "DEFINIZIONE E NOTAZIONI. LEGAME TRA LIMITI DI FUNZIONI E LIMITI DI SUCCESSIONI. UNICITÀ DEL LIMITE. OPERAZIONI CON I LIMITI. FORME INDETERMINATE. LIMITI DELLE FUNZIONI COMPOSTE. LIMITI DELLE FUNZIONI ELEMENTARI AGLI ESTREMI DEL LORO INSIEME DI DEFINIZIONE.\r\n"
				+ "\r\n"
				+ "FUNZIONI CONTINUE\r\n"
				+ "DEFINIZIONE. CONTINUITÀ DELLE FUNZIONI ELEMENTARI. OPERAZIONI CON FUNZIONI CONTINUE. COMPOSIZIONE DI FUNZIONI CONTINUE. TH DELLA PERMANENZA DEL SEGNO. TH DEGLI ZERI. PUNTI DI DISCONTINUITÀ: CLASSIFICAZIONE ED ESEMPI. TH DI WEIERSTRASS. TEOREMI DELL'ESISTENZA DEI VALORI INTERMEDI (DIMOSTRAZIONE SOLO DEL PRIMO). LIMITI NOTEVOLI (DIM).\r\n"
				+ "\r\n"
				+ "DERIVATE\r\n"
				+ "DEFINIZIONE E SIGNIFICATO GEOMETRICO. CONTINUITÀ DELLE FUNZIONI DERIVABILI (DIM). OPERAZIONI CON LE DERIVATE (DIM). DERIVATA DI UNA FUNZIONE COMPOSTA. DERIVATA DELLA FUNZIONE INVERSA. DERIVATE DELLE FUNZIONI ELEMENTARI (DIM). DERIVATE DI ORDINE SUPERIORE. TEOREMI DI DE L'HOPITAL. FORMULA DI TAYLOR.\r\n"
				+ "\r\n"
				+ "APPLICAZIONI DELLE DERIVATE. STUDIO DI FUNZIONI.\r\n"
				+ "MASSIMI E MINIMI RELATIVI DI UNA FUNZIONE REALE DI UNA VARIABILE REALE. TH DI FERMAT (DIM). TH DI ROLLE (DIM). TH DI LAGRANGE (INTERPRETAZIONE GRAFICA). CRITERIO DI MONOTONIA (DIM). CRITERIO DI STRETTA MONOTONIA. CARATTERIZZAZIONE DELLE FUNZIONI COSTANTI IN UN INTERVALLO (DIM). FUNZIONI CONVESSE E CONCAVE. CRITERIO DI CONVESSITÀ. DETERMINAZIONE DEGLI ESTREMI RELATIVI DI UNA FUNZIONE. STUDIO DEL GRAFICO DI UNA FUNZIONE.\r\n"
				+ "\r\n"
				+ "INTEGRAZIONE SECONDO RIEMANN\r\n"
				+ "DEFINIZIONE NEL CASO DI UNA FUNZIONE LIMITATA E NOTAZIONI. INTERPRETAZIONE GEOMETRICA. PROPRIETÀ DI ADDITIVITÀ RISPETTO ALL'INTERVALLO E DI LINEARITÀ. INTEGRABILITÀ DELLE FUNZIONI CONTINUE. TEOREMI DELLA MEDIA(DIM).\r\n"
				+ "\r\n"
				+ "INTEGRALI INDEFINITI\r\n"
				+ "PRIMITIVE. TH FONDAMENTALE DEL CALCOLO INTEGRALE (DIM). CARATTERIZZAZIONE DELLE PRIMITIVE DI UNA FUNZIONE IN UN INTERVALLO (DIM). FORMULA FONDAMENTALE DEL CALCOLO INTEGRALE (DIM). INTEGRALE INDEFINITO. INTEGRAZIONE PER DECOMPOSIZIONE IN SOMMA. INTEGRAZIONE DELLE FUNZIONI RAZIONALI. INTEGRAZIONE PER PARTI. ALCUNI TIPI DI INTEGRAZIONE PER SOSTITUZIONE");
		pf11.setIndice_contenuti("LO STUDENTE ACQUISIRA' LA CONOSCENZA E PADRONANZA DEI CONCETTI PRINCIPALI E DEI METODI CHE STANNO ALLA BASE DELLA RISOLUZIONE DI PROBLEMI DI INTELLIGENZA ARTIFICIALE.\r\n"
				+ "MODELLAZIONE E RAPPRESENTAZIONE DI PROBLEMI DI INTELLIGENZA ARTIFICIALE;\r\n"
				+ "- AGENTI INTELLIGENTI;\r\n"
				+ "- ALGORITMI DI RICERCA;\r\n"
				+ "- ALGORITMI DI RICERCA CON AVVERSARI;\r\n"
				+ "- ALGORITMI EURISTICI E METAEURISTICI;\r\n"
				+ "- ALGORITMI DI APPRENDIMENTO NON SUPERVISIONATO;\r\n"
				+ "- ALGORITMI DI APPRENDIMENTO SUPERVISIONATO;\r\n"
				+ "- METODI DI VALIDAZIONE DI ALGORITMI DI INTELLIGENZA ARTIFICIALE.\r\n"
				+ "\r\n"
				+ "IL CORSO FORNIRÀ LE CONOSCENZE DI BASE SUI SEGUENTI ARGOMENTI:\r\n"
				+ "\r\n"
				+ "RAPPRESENTAZIONE DELLA CONOSCENZA:\r\n"
				+ "- CENNI STORICI SULLA PSICOLOGIA COGNITIVA, SULLA NASCITA DELL’INTELLIGENZA ARTIFICIALE, E SUL RAPPORTO TRA LA PSICOLOGIA COGNITIVA ED INTELLIGENZA ARTIFICIALE\r\n"
				+ "- AGENTI INTELLIGENTI E, QUINDI, RAPPRESENTAZIONE DELLA CONOSCENZA A PARTIRE DA DESCRIZIONI TESTUALI.\r\n"
				+ "\r\n"
				+ "TEORIA BAYESIANA DELLA DECISIONE:\r\n"
				+ "- INTRODUZIONE ALLA PROBABILITÀ;\r\n"
				+ "- LA DECISIONE BAYESIANA;\r\n"
				+ "- IL RISCHIO BAYESIANO;\r\n"
				+ "- DENSITÀ NORMALI E CLASSIFICATORE BAYESIANO.\r\n"
				+ "- RISOLUZIONE DI PROBLEMI TRAMITE ALGORITMI DI RICERCA:\r\n"
				+ "\r\n"
				+ "TECNICHE DI RICERCA INFORMATE;\r\n"
				+ "- TECNICHE DI RICERCA NON INFORMATE;\r\n"
				+ "- TECNICHE DI RICERCA CON AVVERSARI;\r\n"
				+ "- TECNICHE DI RICERCA EURISTICI;\r\n"
				+ "- TECNICHE DI RICERCA METAEURISTICI;\r\n"
				+ "\r\n"
				+ "TECNICHE DI APPRENDIMENTO:\r\n"
				+ "- ESTRAZIONE E RIDUZIONE DELLE CARATTERISTICHE DAI DATI;\r\n"
				+ "- ALGORITMI DI APPRENDIMENTO SUPERVISIONATO, COME ALGORITMI DI MACHINE LEARNING CHE COMPRENDONO TECNICHE DI CLASSIFICAZIONE, VALIDAZIONE E QUALITÀ DEI DATI.\r\n"
				+ "- ALGORITMI DI APPRENDIMENTO NON SUPERVISIONATO, COME ALGORITMI DI CLUSTERING E REGOLE DI ASSOCIAZIONE;\r\n"
				+ "- ANALISI DELLE PRESTAZIONI (ACCURATEZZA VS PRECISIONE, MATRICE DI CONFUSIONE, CURVE ROC, CURVE CMC ECC).\r\n"
				+ "\r\n"
				+ "APPLICAZIONE DI TECNICHE DI INTELLIGENZA ARTIFICIALE IN CONTESTI REALI: PER LO SVOLGIMENTO DI TALI ATTIVITÀ PRATICHE, LO STUDENTE ACQUISIRÀ CONOSCENZE RELATIVE ALL’USO DI VARI STRUMENTI, COME R, PYTHON SKLEARN, WEKA ED ALTRI.");
		pf12.setIndice_contenuti("L'INSEGNAMENTO TRATTERÀ I SEGUENTI ARGOMENTI:\r\n"
				+ "1.FONDAMENTI DI PROGRAMMAZIONE; 1H LEZIONE\r\n"
				+ "2.CONCETTI DI ALGORITMO E PROGRAMMA; 1H LEZIONE\r\n"
				+ "3.ANALISI DEL PROBLEMA; 1H LEZIONE\r\n"
				+ "4.CONCETTI DI SPECIFICA, PRECONDIZIONE, POSTCONDIZIONE; 1H LEZIONE\r\n"
				+ "5.PROGETTAZIONE DELLA SOLUZIONE ATTRAVERSO RAFFINAMENTI SUCCESSIVI E DIVIDE ET IMPERA; 2H LEZIONE\r\n"
				+ "6.COMPILAZIONE E CARICAMENTO DI PROGRAMMI; 2H LEZIONE + 1H LABORATORIO\r\n"
				+ "7.USO DELLE LIBRERIE STANDARD; 2H LEZIONE + 1H LABORATORIO\r\n"
				+ "8.INPUT/OUTPUT; ESPRESSIONI; 2H LEZIONE + 1H LABORATORIO\r\n"
				+ "9.ISTRUZIONI CONDIZIONALI; 2H LEZIONE + 2H LABORATORIO\r\n"
				+ "10.CICLI; 2H LEZIONE + 2H LABORATORIO\r\n"
				+ "11.TIPI DI DATI; 2H LEZIONE + 2H LABORATORIO\r\n"
				+ "12.ARRAY E FILE; 6H LEZIONE + 3H LABORATORIO\r\n"
				+ "13.DECOMPOSIZIONE TOP-DOWN E DEFINIZIONE DI FUNZIONI PERSONALI; 2H LEZIONE + 1H LABORATORIO\r\n"
				+ "14.DURATA E VISIBILITÀ DELLE VARIABILI; 2H LEZIONE + 1H LABORATORIO\r\n"
				+ "15.CENNI SU STACK E RECORD DI ATTIVAZIONE; 2H LEZIONE + 1H LABORATORIO\r\n"
				+ "16.PUNTATORI; 6H LEZIONE + 4H LABORATORIO\r\n"
				+ "17.ALLOCAZIONE E DEALLOCAZIONE DELLA MEMORIA; 5H LEZIONE + 2H LABORATORIO\r\n"
				+ "18.STRINGHE; LE STRUTTURE; 5H LEZIONE + 2H LABORATORIO\r\n"
				+ "19.INTRODUZIONE ALLA RICORSIONE. 2H LEZIONE + 1H LABORATORIO\r\n"
				+ "20.UTILIZZO DEL LINGUAGGIO C \r\n"
				+ "\r\n"
				+ "TOTALE: 48H LEZIONE + 24H LABORATORIO");
		pf13.setIndice_contenuti("	CONCETTI DI BASE DI PYTHON (4 ORE)\r\n"
				+ "PROGRAMMAZIONE ORIENTATA AGLI OGGETTI IN PYTHON (3 ORE)\r\n"
				+ "ECCEZIONI E ASSERZIONI (2 ORE)\r\n"
				+ "PROGRAMMAZIONE FUNZIONALE (5 ORE)\r\n"
				+ "CREATIONAL DESIGN PATTERN (3 ORE)\r\n"
				+ "STRUCTURAL DESIGN PATTERN (4 ORE)\r\n"
				+ "BEHAVIORAL DESIGN PATTERN (6 ORE)\r\n"
				+ "INTROSPECTION (4 ORE)\r\n"
				+ "GENERATORI, COROUTINE (3 ORE)\r\n"
				+ "GESTIONE DELLA MEMORIA, GARBAGE COLLECTION (2 ORE)\r\n"
				+ "INPUT-OUTPUT, SERIALIZZAZIONE (2 ORE)\r\n"
				+ "MULTIPROCESSING (3 ORE)\r\n"
				+ "MULTITHREADING (3 ORE)\r\n"
				+ "NETWORKING (4 ORE)");
		pf14.setIndice_contenuti("INTRODUZIONE DEL CONCETTO DI “INTERAZIONE UOMO MACCHINA”. MODELLI O FRAMEWORK DI INTERAZIONE. GLI STILI DELL’INTERAZIONE. IL CONTESTO SOCIALE DELL’INTERAZIONE. CENNI SULL’ERGONOMIA.\r\n"
				+ "LA PROGETTAZIONE DELLE INTERFACCE UOMO - SISTEMA. PRINCIPI DI PROGETTAZIONE DELLE INTERFACCE. LINEE GUIDA E METODOLOGIE PER L’INDIVIDUAZIONE DEI PROFILI UTENTE. ANALISI DEI TASK E SCENARI DI UTILIZZO.\r\n"
				+ "PARADIGMI DI INTERAZIONE PER L’USABILITÀ: PROSPETTIVA STORICA . IL PARADIGMA DI MANIPOLAZIONE DIRETTA. L’INTERAZIONE MULTIMODALE. L’INTERAZIONE COLLABORATIVA. CENNI A PARADIGMI PIÙ AVANZATI DI INTERAZIONE, QUALI L’UBIQUITOUS COMPUTING, LA REALTÀ AUMENTATA E LA REALTÀ VIRTUALE.\r\n"
				+ "PRINCIPI DI AUSILIO ALL’USABILITÀ: LA “CAPACITÀ DI APPRENDIMENTO”. LA “FLESSIBILITÀ”. LA “ROBUSTEZZA”. ACCESSIBILITÀ E LINEE GUIDA.\r\n"
				+ "STRUMENTI DI SUPPORTO ALL’IMPLEMENTAZIONE DEI SISTEMI INTERATTIVI: I SISTEMI A FINESTRE. I TOOLKIT DI INTERAZIONE. GLI USER INTEFACE MANAGEMENT SYSTEMS. IL DESIGN ITERATIVO E LE TECNICHE DI PROTOTIPAZIONE DELLE APPLICAZIONI INTERATTIVE. I PAPER SKETCH DI INTERFACCE UTENTE.\r\n"
				+ "TECNICHE DI VALUTAZIONE DEI SISTEMI INTERATTIVI. CONFRONTO TRA VALUTAZIONE SUL CAMPO E VALUTAZIONE IN LABORATORIO. TECNICHE DI VALUTAZIONE DA APPLICARE IN FASE DI DESIGN E TECNICHE DA APPLICARE A IMPLEMENTAZIONE AVVENUTA.");
		pf15.setIndice_contenuti("1.LA PROGRAMMAZIONE LINEARE (PL):\r\n"
				+ "- RICHIAMI DI ALGEBRA LINEARE; OPERAZIONI SULLE MATRICI; POLIEDRI; DIREZIONI, DIREZIONI ESTREME; TEOREMA DELLA RAPPRESENTAZIONE; PASSAGGIO DAL PROBLEMA REALE AL MODELLO DI OTTIMIZZAZIONE; IL METODO DEL SIMPLESSO: PUNTI ESTREMI ED OTTIMALITÀ; CONDIZIONI DI OTTIMALITÀ E ILLIMITATEZZA. L'ALGEBRA DEL METODO DEL SIMPLESSO; LA RICERCA DI UNA SOLUZIONE AMMISSIBILE DI BASE INIZIALE; IL METODO DELLE DUE FASI; IL METOTO DEL BIG M. DEGENERAZIONE E CICLI; CONVERGENZA DEL METODO DEL SIMPLESSO. UTILIZZO DEL PROGRAMMA EXCEL PER LA SOLUZIONE DI PROBLEMI DI PROGRAMMAZIONE LINEARE.\r\n"
				+ "\r\n"
				+ "- DUALITÀ: FORMULAZIONE DEL PROBLEMA DUALE; COSTI RIDOTTI; TEOREMA DEBOLE E TEOREMA FORTE DELLA DUALITÀ; GLI SCARTI COMPLEMENTARI; RELAZIONI PRIMALE-DUALE; INTERPRETAZIONE ECONOMICA DEL DUALE.\r\n"
				+ "- ANALISI DELLA SENSITIVITÀ ED ANALISI PARAMETRICA: ANALISI POST-OTTIMALE; VARIAZIONE DELLA SOLUZIONE OTTIMA E DEL VALORE OTTIMO DI UN PROBLEMA DI PL AL VARIARE DEI DATI.\r\n"
				+ "\r\n"
				+ "2. OTTIMIZZAZIONE SU RETE:\r\n"
				+ "- PROBLEMI DI FLUSSO SU RETE: CAMMINI MINIMI. ALBERO DI COPERTURA DI PESO MINIMO. MASSIMO FLUSSO. TRASPORTO. ASSEGNAMENTO. MODELLI MATEMATICI ED ALGORITMI.");
		pf16.setIndice_contenuti("CONTENUTI DEL CORSO: \r\n "
				+ "- MASTERIZZAZIONE HTML ; \r\n"
				+ "- MASTER HTML 5 ; \r\n "
				+ "- CREARE PAGINE WEB DA ZERO ; \r\n "
				+ "- PRIMI PASSI NELLO SVILUPPO WEB ; \r\n "
				+ "- SCOPRI COME UTILIZZARE IN MODO APPROFONDITO TUTTI I TAG PIU' IMPORTANTI ; \r\n"
				+ "- HTML MODERNO IN PROFONDITA' ; \r\n "
				+ "- MOLTO ALTRO ANCORA .");
		pf17.setIndice_contenuti("MODELLI AVANZATI E TECNOLOGIE DI BASI DI DATI UTILIZZATE NEL CONTESTO DEI SISTEMI INFORMATIVI AZIENDALI:\r\n"
				+ "•ORGANIZZAZIONE FISICA DEI DATI ED INDICIZZAZIONE\r\n"
				+ "•CONCORRENZA\r\n"
				+ "•GESTIONE DELLE TRANSAZIONI\r\n"
				+ "•BASI DI DATI DISTRIBUITE\r\n"
				+ "•ASPETTI DI PRIVACY E CONTROLLO DELL’ACCESSO\r\n"
				+ "\r\n"
				+ "TEMATICHE INERENTI ASPETTI EVOLUTI DI GESTIONE DEI DATI:\r\n"
				+ "•DATABASE SEMI STRUTTURATI\r\n"
				+ "•INFORMATION RETRIEVAL\r\n"
				+ "•DATA WAREHOUSE\r\n"
				+ "•SISTEMI DI BUSINESS INTELLIGENCE\r\n"
				+ "•BASI DI DATI XML E MULTIMEDIALI\r\n"
				+ "•BIG DATA E NOSQL");
		pf18.setIndice_contenuti("IL CORSO INCLUDE ORE DI DIDATTICA NELLA FORMA DI LEZIONI E ORE DI ESERCITAZIONI GUIDATE DURANTE LE QUALI GLI STUDENTI VERIFICANO DIRETTAMENTE IN UN AMBIENTE DI EMULAZIONE CIÒ CHE IL DOCENTE HA PRESENTATO NEL CORSO DELLE LEZIONI (CON UN APPROCCIO LEARNING-BY-DOING).\r\n"
				+ "\r\n"
				+ "GLI ARGOMENTI AFFRONTATI NELLE LEZIONI IN AULA SONO:\r\n"
				+ "\r\n"
				+ "LEZIONI FRONTALI\r\n"
				+ "•INTRODUZIONE E PANORAMICA DEL CORSO [PFLEEGER SEZIONE 1; ANDERSON CAPITOLO 1]\r\n"
				+ "•ELEMENTI DI BASE DI NETWORKING [PFLEEGER SEZIONE 7.0, 7.1 (PP. 376-396)]\r\n"
				+ "•ANALISI ED INTERCETTAZIONE DEL TRAFFICO\r\n"
				+ "•AUTENTICAZIONE, AUTORIZZAZIONE E ACCOUNTING [KAUFMAN CAPITOLI 9 E 10]\r\n"
				+ "•SICUREZZA DELLE COMUNICAZIONI IN RETE [PFLEEGER CAPITOLO 7.3]\r\n"
				+ "•NETWORK ACCESS CONTROL [PFLEEGER SEZIONE 7.4; PFLEEGER PP. 449-450]\r\n"
				+ "•SPOOFING E FURTO DI IDENTITÀ [ANDERSON CAPITOLO 2]\r\n"
				+ "•L’ANONIMATO IN RETE [PFLEEGER PP. 150-160; ANDERSON CAPITOLO 17]\r\n"
				+ "•PROBLEMI DI SICUREZZA NEGLI INTERNET PROTOCOLS [CHESWICK CAPITOLI 2 E 3]\r\n"
				+ "•I PIÙ COMUNI ATTACCHI IN RETE [PFLEEGER PP. 396-424]\r\n"
				+ "•ATTACCHI DENIAL OF SERVICE [PFLEEGER PP. 427-432]\r\n"
				+ "•RICONOSCIMENTO ED INDIVIDUAZIONE DEGLI ATTACCHI [PFLEEGER CAPITOLO 7.5 (PP. 484-490); ANDERSON CAPITOLO 21.4.3/21.4.4]\r\n"
				+ "•TRACCIAMENTO A RITROSO DEGLI ATTACCHI ED INDIVIDUAZIONE DELLE LORO ORIGINI\r\n"
				+ "•MALWARE E BOTNETS [STALLINGS CAPITOLO 19]\r\n"
				+ "•VIRUSES E WORMS [PFLEEGER CAPITOLO 3.3 (PP. 111-141); ANDERSON CAPITOLO 21.3]\r\n"
				+ "•SICUREZZA E TECNICHE DI DIFESA PER SISTEMI WWW [KAUFMAN CAPITOLO 25, PFLEEGER PP. 424-427, PFLEEGER PP. 433-437]\r\n"
				+ "•INTRUSION DETECTION/PREVENTION SYSTEMS [STALLINGS CAPITOLO 18]\r\n"
				+ "•FIREWALLS [STALLINGS CAPITOLO 20 E KAUFMAN CAPITOLO 23]\r\n"
				+ "•ANOMALY DETECTION\r\n"
				+ "\r\n"
				+ "ATTIVITÀ DI LABORATORIO\r\n"
				+ "•EMULAZIONE DI SISTEMI COMPLESSI IN RETE CON GNS3\r\n"
				+ "•IMPLEMENTAZIONE DI REGOLE DI FILTRAGGIO, POLITICHE E STRATEGIE DI CONTROLLO ACCESSI SUI PRINCIPALI ROUTER COMMERCIALI\r\n"
				+ "•IMPLEMENTAZIONE DI MECCANISMI DI SICUREZZA PERIMETRALE\r\n"
				+ "•ESERCIZI DI SCANSIONE VULNERABILITÀ DI UNA RETE\r\n"
				+ "•INSTALLAZIONE E CONFIGURAZIONE DI UN SEMPLICE FIREWALL");
		pf19.setIndice_contenuti("•DEFINIZIONI FONDAMENTALI DI MANAGEMENT: PROGETTO, PROJECT MANAGEMENT, PORTFOLIO E PROGRAMMA. IL RUOLO DEL PROJECT MANAGER. IL PROJECT MANAGEMENT NELL’AMBITO DELL’INFORMATION TECHNOLOGY.\r\n"
				+ "•I GRUPPI DI PROCESSI FONDAMENTALI DEL PROJECT MANAGEMENT: INIZIO, PIANIFICAZIONE, ESECUZIONE, MONITORAGGIO E CONTROLLO, CHIUSURA.\r\n"
				+ "•LA GESTIONE DELLE AREE DI CONOSCENZA: L’INTEGRAZIONE, LO SCOPE, IL TEMPO, IL COSTO, LA QUALITÀ, LE RISORSE UMANE, LA COMUNICAZIONE, IL RISCHIO, GLI ACQUISTI, GLI STAKEHOLDER.\r\n"
				+ "•ATTIVITÀ DI GESTIONE IN UN PROGETTO SOFTWARE; LA WORK BREAKDOWN STRUCTURE (WBS); IL PIANO DI GESTIONE DEL PROGETTO SOFTWARE; PROCESSI DI SVILUPPO, PROCESSI DI MANAGEMENT E PROCESSI D’INTEGRAZIONE.\r\n"
				+ "•MISURAZIONE DEL SOFTWARE; PARADIGMA GOAL-QUESTION-METRIC; CLASSIFICAZIONE DELLE METRICHE DEL SOFTWARE; MISURE DI SIZE FUNZIONALI (FPA E COSMIC), STIMA DELL’EFFORT.\r\n"
				+ "•SISTEMI DI GESTIONE QUALITÀ E MODELLI, STANDARD PER LA QUALITÀ DEL PRODOTTO SOFTWARE E RELATIVE CARATTERISTICHE. SOFTWARE PROCESS IMPROVEMENT, REQUISITI DI MISURAZIONE DEL CMMI.\r\n"
				+ "•IL CICLO DI VITA DEL SOFTWARE. MODELLI DEL CICLO DI VITA DEL SOFTWARE; METODOLOGIE AGILI, SCRUM E AGILE PROJECT MANAGEMENT.");
		pf20.setIndice_contenuti("I NUMERI REALI\r\n"
				+ "ASSIOMI DEI NUMERI REALI E CONSEGUENZE. NUMERI NATURALI, INTERI E RAZIONALI. INSIEMI NUMERICI: INSIEME LIMITATO, MASSIMO E MINIMO, ESTREMO INFERIORE E SUPERIORE. UNICITÀ DEL MINIMO (DIM). TH DI ESISTENZA DELL'ESTREMO SUPERIORE (DIM). INSIEMI NON LIMITATI. INTERVALLI. PROPRIETÀ DI ARCHIMEDE (DIM). NON COMPLETEZZA DELL'INSIEME DEI NUMERI RAZIONALI (DIM).\r\n"
				+ "\r\n"
				+ "FUNZIONI REALI DI UNA VARIABILE REALE\r\n"
				+ "DEFINIZIONE E NOTAZIONI. ESTREMI. RAPPRESENTAZIONE CARTESIANA. FUNZIONI PARI, FUNZIONI DISPARI E FUNZIONI PERIODICHE. ALGEBRA DELLE FUNZIONI. COMPOSIZIONE DI FUNZIONI. FUNZIONI INVERTIBILI. FUNZIONI MONOTONE. INVERTIBILITÀ DELLE FUNZIONI MONOTONE(DIM).\r\n"
				+ "\r\n"
				+ "FUNZIONI ELEMENTARI\r\n"
				+ "FUNZIONE LINEARE. FUNZIONE VALORE ASSOLUTO. DISUGUAGLIANZA TRIANGOLARE. FUNZIONI POTENZA. FUNZIONE ESPONENZIALE. FUNZIONE LOGARITMO. FUNZIONI TRIGONOMETRICHE E TRIGONOMETRICHE INVERSE.\r\n"
				+ "\r\n"
				+ "SUCCESSIONI NUMERICHE\r\n"
				+ "DEFINIZIONE E NOTAZIONI. RAPPRESENTAZIONE GRAFICA DI UNA SUCCESSIONE. SUCCESSIONI CONVERGENTI: DEFINIZIONE ED ESEMPI. TH SULL'UNICITÀ DEL LIMITE (DIM). SUCCESSIONI DIVERGENTI: DEFINIZIONI ED ESEMPI. VERIFICHE DI LIMITI. SUCCESSIONI NON REGOLARI. SUCCESSIONI LIMITATE. LIMITATEZZA DELLE SUCCESSIONI CONVERGENTI(DIM). OPERAZIONI CON I LIMITI DI SUCCESSIONI (DIMOSTRAZIONE DELLA SOMMA E DEL PRODOTTO SOLO NEL CASO DELLA CONVERGENZA). FORME INDETERMINATE. TH DELLA PERMANENZA DEL SEGNO E COROLLARI(DIM). TH DEI CARABINIERI (DIM). TH DEL PRODOTTO DI UNA SUCCESSIONE LIMITATA PER UNA INFINITESIMA. SUCCESSIONI MONOTONE E RELATIVO TH (DIM). IL NUMERO E. ALCUNI LIMITI NOTEVOLI. CRITERIO DEL RAPPORTO E SUE APPLICAZIONI. INFINITI DI ORDINE CRESCENTE. SUCCESSIONI ESTRATTE. TH DI BOLZANO-WEIERSTRASS.\r\n"
				+ "LIMITI DI FUNZIONI\r\n"
				+ "DEFINIZIONE E NOTAZIONI. LEGAME TRA LIMITI DI FUNZIONI E LIMITI DI SUCCESSIONI. UNICITÀ DEL LIMITE. OPERAZIONI CON I LIMITI. FORME INDETERMINATE. LIMITI DELLE FUNZIONI COMPOSTE. LIMITI DELLE FUNZIONI ELEMENTARI AGLI ESTREMI DEL LORO INSIEME DI DEFINIZIONE.\r\n"
				+ "\r\n"
				+ "FUNZIONI CONTINUE\r\n"
				+ "DEFINIZIONE. CONTINUITÀ DELLE FUNZIONI ELEMENTARI. OPERAZIONI CON FUNZIONI CONTINUE. COMPOSIZIONE DI FUNZIONI CONTINUE. TH DELLA PERMANENZA DEL SEGNO. TH DEGLI ZERI. PUNTI DI DISCONTINUITÀ: CLASSIFICAZIONE ED ESEMPI. TH DI WEIERSTRASS. TEOREMI DELL'ESISTENZA DEI VALORI INTERMEDI (DIMOSTRAZIONE SOLO DEL PRIMO). LIMITI NOTEVOLI (DIM).\r\n"
				+ "\r\n"
				+ "DERIVATE\r\n"
				+ "DEFINIZIONE E SIGNIFICATO GEOMETRICO. CONTINUITÀ DELLE FUNZIONI DERIVABILI (DIM). OPERAZIONI CON LE DERIVATE (DIM). DERIVATA DI UNA FUNZIONE COMPOSTA. DERIVATA DELLA FUNZIONE INVERSA. DERIVATE DELLE FUNZIONI ELEMENTARI (DIM). DERIVATE DI ORDINE SUPERIORE. TEOREMI DI DE L'HOPITAL. FORMULA DI TAYLOR.\r\n"
				+ "\r\n"
				+ "APPLICAZIONI DELLE DERIVATE. STUDIO DI FUNZIONI.\r\n"
				+ "MASSIMI E MINIMI RELATIVI DI UNA FUNZIONE REALE DI UNA VARIABILE REALE. TH DI FERMAT (DIM). TH DI ROLLE (DIM). TH DI LAGRANGE (INTERPRETAZIONE GRAFICA). CRITERIO DI MONOTONIA (DIM). CRITERIO DI STRETTA MONOTONIA. CARATTERIZZAZIONE DELLE FUNZIONI COSTANTI IN UN INTERVALLO (DIM). FUNZIONI CONVESSE E CONCAVE. CRITERIO DI CONVESSITÀ. DETERMINAZIONE DEGLI ESTREMI RELATIVI DI UNA FUNZIONE. STUDIO DEL GRAFICO DI UNA FUNZIONE.\r\n"
				+ "\r\n"
				+ "INTEGRAZIONE SECONDO RIEMANN\r\n"
				+ "DEFINIZIONE NEL CASO DI UNA FUNZIONE LIMITATA E NOTAZIONI. INTERPRETAZIONE GEOMETRICA. PROPRIETÀ DI ADDITIVITÀ RISPETTO ALL'INTERVALLO E DI LINEARITÀ. INTEGRABILITÀ DELLE FUNZIONI CONTINUE. TEOREMI DELLA MEDIA(DIM).\r\n"
				+ "\r\n"
				+ "INTEGRALI INDEFINITI\r\n"
				+ "PRIMITIVE. TH FONDAMENTALE DEL CALCOLO INTEGRALE (DIM). CARATTERIZZAZIONE DELLE PRIMITIVE DI UNA FUNZIONE IN UN INTERVALLO (DIM). FORMULA FONDAMENTALE DEL CALCOLO INTEGRALE (DIM). INTEGRALE INDEFINITO. INTEGRAZIONE PER DECOMPOSIZIONE IN SOMMA. INTEGRAZIONE DELLE FUNZIONI RAZIONALI. INTEGRAZIONE PER PARTI. ALCUNI TIPI DI INTEGRAZIONE PER SOSTITUZIONE");
		pf21.setIndice_contenuti("MODELLAZIONE CONCETTUALE E LOGICA DI BASI DI DATI:\r\n"
				+ "- IL MODELLO ENTITÀ/RELAZIONI\r\n"
				+ "- IL MODELLO RELAZIONALE\r\n"
				+ "- TECNICHE DI RISTRUTTURAZIONE\r\n"
				+ "- REGOLE DI MAPPING ER-RELAZIONALE\r\n"
				+ "- STRUMENTI AUTOMATICI DI SUPPORTO ALLA PROGETTAZIONE.\r\n"
				+ "\r\n"
				+ "LINGUAGGI DI INTERROGAZIONE E METODOLOGIE DI PROGETTAZIONE:\r\n"
				+ "- ALGEBRA RELAZIONALE\r\n"
				+ "- IL LINGUAGGIO SQL\r\n"
				+ "- LE LIBRERIE DI FUNZIONI JDBC\r\n"
				+ "- LE REGOLE DI NORMALIZZAZIONE DELLE BASI DI DATI.\r\n"
				+ "\r\n"
				+ "LABORATORIO\r\n"
				+ "STRUMENTI CASE DI SUPPORTO ALLA PROGETTAZIONE\r\n"
				+ "DBMS RELAZIONALE MYSQL");
		pf22.setIndice_contenuti("PARTE I: INTRODUZIONE ALL’INTELLIGENZA ARTIFICIALE\r\n"
				+ "AGENTI INTELLIGENTI\r\n"
				+ " \r\n"
				+ "PARTE II: RISOLUZIONE DI PROBLEMI\r\n"
				+ "RISOLVERE I PROBLEMI CON LA RICERCA\r\n"
				+ "RICERCA INFORMATA\r\n"
				+ "RICERCA CON AVVERSARI\r\n"
				+ " \r\n"
				+ "PARTE III: CONOSCENZA E RAGIONAMENTO\r\n"
				+ "AGENTI LOGICI\r\n"
				+ "LOGICA DEL PRIMO ORDINE\r\n"
				+ "L'INFERENZA NELLA LOGICA DEL PRIMO ORDINE\r\n"
				+ "RAPPRESENTAZIONE DELLA CONOSCENZA\r\n"
				+ "\r\n"
				+ "PARTE IV: CONOSCENZA INCERTA E RAGIONAMENTO\r\n"
				+ "INCERTEZZA\r\n"
				+ "RAGIONAMENTO PROBABILISTICO\r\n"
				+ " \r\n"
				+ "PARTE V: APPRENDIMENTO\r\n"
				+ "APPRENDIMENTO DALLE OSSERVAZIONI\r\n"
				+ "CONOSCENZA E APPRENDIMENTO\r\n"
				+ "RETI NEURALI\r\n"
				+ "MACCHINE KERNEL");
		pf23.setIndice_contenuti("CONCETTI DI BASE DI PYTHON (4 ORE)\r\n"
				+ "PROGRAMMAZIONE ORIENTATA AGLI OGGETTI IN PYTHON (3 ORE)\r\n"
				+ "ECCEZIONI E ASSERZIONI (2 ORE)\r\n"
				+ "PROGRAMMAZIONE FUNZIONALE (5 ORE)\r\n"
				+ "CREATIONAL DESIGN PATTERN (3 ORE)\r\n"
				+ "STRUCTURAL DESIGN PATTERN (4 ORE)\r\n"
				+ "BEHAVIORAL DESIGN PATTERN (6 ORE)\r\n"
				+ "INTROSPECTION (4 ORE)\r\n"
				+ "GENERATORI, COROUTINE (3 ORE)\r\n"
				+ "GESTIONE DELLA MEMORIA, GARBAGE COLLECTION (2 ORE)\r\n"
				+ "INPUT-OUTPUT, SERIALIZZAZIONE (2 ORE)\r\n"
				+ "MULTIPROCESSING (3 ORE)\r\n"
				+ "MULTITHREADING (3 ORE)\r\n"
				+ "NETWORKING (4 ORE)");
		pf24.setIndice_contenuti("IL CORSO È PRINCIPALMENTE BASATO SUL PROTOTYPING E COSTRUZIONE DI ROBOT, PROGRAMMAZIONE DI ROBOT E ALGORITMI PER IL CONTROLLO DI UN ROBOT.\r\n"
				+ "IN PARTICOLARE, I SEGUENTI ARGOMENTI SONO SVILUPPATI:\r\n"
				+ "• FONDAMENTI DI PROGRAMMAZIONE ROBOT E TIPOLOGIE DI ROBOT\r\n"
				+ "• PROTOTIPIZZAZIONE E MONTAGGIO DI UN ROBOT\r\n"
				+ "• TOOL DI SVILUPPO: SIMULATORI, CAD E STAMPA 3D\r\n"
				+ "• MATERIALI UTILIZZATI PER COSTRUIRE ROBOT\r\n"
				+ "• GESTIONE DELLE BATTERIE\r\n"
				+ "• METODOLOGIE PER LA PROGRAMMAZIONE DI UN ROBOT: MODELLI STATECHART\r\n"
				+ "• LINGUAGGI DI PROGRAMMAZIONE PER LA ROBOTICA\r\n"
				+ "• INTERFACCIARE I ROBOT: COMUNICAZIONI TRA I MICROCONTROLLORI, INTERAGIRE CON UN CONTROLLORE DI MOTORI, SHIELD DI PROTEZIONE\r\n"
				+ "• CONTROLLO UTENTE: CONTROLLO WIRED, CONTROLLO A INFRAROSSI, CONTROLLO BASATO SU RADIOFREQUENZA: BLUETOOTH E WIFI\r\n"
				+ "• CONTROLLO AUTONOMO: CONTROLLO INTELLIGENTE BASATO SUL PROCESSING DELLE IMMAGINI, MODELLI DI MACHINE LEARNING E BASATO SUI SENSORI\r\n"
				+ "• SENSORI: SENSORE CONTATTO, SENSORI DI DISTANZA E DI RIFLESSIONE, SENSORI DI ORIENTAMENTO E POSIZIONE, SENSORE CAMERA\r\n"
				+ "• MOTORI ELETTRICI: STEPPING / SERVO / LINEARI, GESTIONE DELLA GUIDA\r\n"
				+ "• ESEMPI DI LINE BOT, WALL BOT, E ARM BOT\r\n"
				+ "• ROBOT MOTION PLANNING: MOVIMENTO DEL BRACCIO (CINEMATICA INVERSA E DIRETTA, CONTROLLO A N-JOINT), NAVIGAZIONE DEL ROBOT (PIANIFICAZIONE DEL PERCORSO, TRACCIAMENTO DEL PERCORSO, EVITARE GLI OSTACOLI)\r\n"
				+ "• DECISION MAKING: SELEZIONE DELLE AZIONI DEL ROBOT, SELEZIONE DELLA DIREZIONE/ SELEZIONE DEL PERCORSO\r\n"
				+ "• ALGORITMI PER IL CONTROLLO DI UN ROBOT");
		pf25.setIndice_contenuti("ARGOMENTI TRATTATI: \r\n"
				+ "- INTRODUZIONE AL LINGUAGGIO C++ ; \r\n"
				+ "- LE BASI DEL LINGUAGGIO C++ ; \r\n"
				+ "- COSTRUTTI SELETTIVI ; \r\n"
				+ "- COSTRUTTI ITERATIVI ; \r\n"
				+ "- I DATI STRUTTURATI ; \r\n"
				+ "- PUNTATORI E MEMORIA DINAMICA ; \r\n"
				+ "- FUNZIONI E PROCEDURE ; \r\n"
				+ "- PROGETTI E LIBRERIE ; \r\n"
				+ "- LETTURA E SCRITTURA SU FILE ;\r\n"
				+ "- ALTRO ANCORA .");
		pf26.setIndice_contenuti("ARGOMENTI TRATTATI: \r\n"
				+ "- CONCETTI BASE: DETERMINANTE E RANGO; \r\n"
				+ "- SISTEMI LINEARI; \r\n"
				+ "- SPAZI, SOTTOSPAZI, GENERATORI E BASI; \r\n"
				+ "- INTRODUZIONE ALLE APPLICAZIONI LINEARI; \r\n"
				+ "- STUDIO DI APPLICAZIONE LINEARE; \r\n"
				+ "- APPROFONDIMENTO SULLE APPLICAZIONI LINEARI; \r\n"
				+ "- ALTRO ANCORA.");
		pf27.setIndice_contenuti("ARGOMENTI TRATTATI: \r\n"
				+ "- PIANO CARTESIANO; \r\n"
				+ "- SISTEMA BIDIMENSIONALE; \r\n"
				+ "- RETTE; - CIRCONFERENZE; \r\n"
				+ "- PARABOLE; \r\n"
				+ "- ELISSI; \r\n"
				+ "- HIPERBOLE.");
		pf28.setIndice_contenuti("INSIEMI. \r\n"
				+ "OPERAZIONI SUGLI INSIEMI: UNIONE, INTERSEZIONE, DIFFERENZA, DIFFERENZA SIMMETRICA, PRODOTTO CARTESIANO. \r\n"
				+ "INSIEME DELLE PARTI DI UN INSIEME. \r\n"
				+ "PARTIZIONI DI UN INSIEME. \r\n"
				+ "CORRISPONDENZE E APPLICAZIONI. \r\n"
				+ "IMMAGINI E CONTROIMMAGINI. ");
		pf29.setIndice_contenuti("Indice del corso: \r\n"
				+ "- Programmare; \r\n"
				+ "- Programmare in Go; \r\n"
				+ "- Programmare in Golang; \r\n"
				+ "- Go; - Golang; \r\n"
				+ "- Programmazione.");
		pf30.setIndice_contenuti("- Come far girare le Goroutine e comunicare i dati tra di loro. \r\n"
				+ "- Come evitare condizioni di gara e deadlock. \r\n"
				+ "- Come sincronizzare l'esecuzione di Goroutine. \r\n"
				+ "- Come funziona l'utilità di pianificazione Go. \r\n"
				+ "- Come costruire pipeline di streaming con Goro...");
		
		pf0.setDescrizione("Questo corso ha l\'obiettivo di insegnarti a creare siti web.");
		pf1.setDescrizione("Questo corso ha l'obiettivo di insegnarti come ragiona un computer.");
		pf2.setDescrizione("Questo corso ha l'obiettivo di insegnarti la statistica e la probabilita\'.");
		pf3.setDescrizione("Questo corso ha l'obiettivo di insegnarti le strutture di base.");
		pf4.setDescrizione("Questo corso ha l'obiettivo di insegnarti la programmazione object oriented.");
		pf5.setDescrizione("Questo corso ha l'obiettivo di insegnarti come creare un videogame.");
		pf6.setDescrizione("Questo corso ha l'obiettivo di insegnarti la Macchina di turing e gli automi.");
		pf7.setDescrizione("Questo corso ha l'obiettivo di insegnarti gli algoritmi per la sicurezza informatica.");
		pf8.setDescrizione("Questo corso ha l'obiettivo di insegnarti cosa e\' una Base di Dati.");
		pf9.setDescrizione("Questo corso ha l'obiettivo di insegnarti le fondamenta di visione biometrica e artificiale.");
		pf10.setDescrizione("Questo corso ha l'obiettivo di insegnarti l\'analisi matematica.");
		pf11.setDescrizione("Questo corso ha l'obiettivo di insegnarti le fondamenta dell'intelligenza artificiale.");
		pf12.setDescrizione("Questo corso ha l'obiettivo di insegnarti le fondamenta della programmazione.");
		pf13.setDescrizione("Questo corso ha l'obiettivo di insegnarti dei concetti avanzati della programmazione.");
		pf14.setDescrizione("Questo corso ha l'obiettivo di insegnarti le principali tecniche di analisi dell'usabilità e dell'accessibilità di interfacce utente.");
		pf15.setDescrizione("Questo corso ha l'obiettivo di insegnarti cosa e' la ricerca operativa.");
		pf16.setDescrizione("Questo corso ha l'obiettivo di insegnarti tutto sull\'HTML.");
		pf17.setDescrizione("Questo corso ha l'obiettivo di insegnarti dei concetti avanzati sulle Basi di Dati.");
		pf18.setDescrizione("Questo corso ha l'obiettivo di insegnarti cosa e\' la Cyber sicurezza");
		pf19.setDescrizione("Questo corso ha l'obiettivo di insegnarti a come gestire i progetti software.");
		pf20.setDescrizione("Questo corso ha l'obiettivo di insegnarti dei concetti avanzati sull\'analisi matematica.");
		pf21.setDescrizione("Questo corso ha l'obiettivo di insegnarti i concetti base sulle Basi di Dati.");
		pf22.setDescrizione("Questo corso ha l'obiettivo di insegnarti cosa e\' l\'intelligenza artificiale.");
		pf23.setDescrizione("Questo corso ha l'obiettivo di insegnarti dei concetti avanzati sulla programmazione.");
		pf24.setDescrizione("Questo corso ha l'obiettivo di insegnarti a programmare un robot.");
		pf25.setDescrizione("Questo corso ha l'obiettivo di insegnarti il linguaggio di programmazione c++.");
		pf26.setDescrizione("Questo corso ha l'obiettivo di insegnarti cosa e\' l\'algebra lineare.");
		pf27.setDescrizione("Questo corso ha l'obiettivo di insegnarti cosa e\' la geometria analitica.");
		pf28.setDescrizione("Questo corso ha l'obiettivo di insegnarti cosa e\' la matematica discreta.");
		pf29.setDescrizione("Questo corso ha l'obiettivo di insegnarti il linguaggio di programmazione GO.");
		pf30.setDescrizione("Questo corso ha l'obiettivo di insegnarti la concorrenza nel linguaggio di programmazione GO.");
		
		pf0.setCosto(5.0D);   pf1.setCosto(10.0D);  pf2.setCosto(15.0D);  pf3.setCosto(20.0D);  pf4.setCosto(25.0D); 
		pf5.setCosto(30.0D);  pf6.setCosto(30.5D);  pf7.setCosto(25.5D);  pf8.setCosto(20.5D);  pf9.setCosto(15.5D); 
		pf10.setCosto(10.5D); pf11.setCosto(5.5D);  pf12.setCosto(5.0D);  pf13.setCosto(10.0D); pf14.setCosto(15.0D); 
		pf15.setCosto(20.0D); pf16.setCosto(25.0D); pf17.setCosto(30.0D); pf18.setCosto(30.5D); pf19.setCosto(25.5D); 
		pf20.setCosto(20.5D); pf21.setCosto(15.5D); pf22.setCosto(10.5D); pf23.setCosto(5.5D);  pf24.setCosto(5.0D); 
		pf25.setCosto(10.0D); pf26.setCosto(15.0D); pf27.setCosto(20.0D); pf28.setCosto(25.0D); pf29.setCosto(30.0D);
		pf30.setCosto(30.5D);
		
		pf0.setNum_lezioni(5);   pf1.setNum_lezioni(10);  pf2.setNum_lezioni(15);  pf3.setNum_lezioni(20);  
		pf4.setNum_lezioni(25);  pf5.setNum_lezioni(30);  pf6.setNum_lezioni(30);  pf7.setNum_lezioni(25);  
		pf8.setNum_lezioni(20);  pf9.setNum_lezioni(15);  pf10.setNum_lezioni(10); pf11.setNum_lezioni(5);  
		pf12.setNum_lezioni(5);  pf13.setNum_lezioni(10); pf14.setNum_lezioni(15); pf15.setNum_lezioni(20); 
		pf16.setNum_lezioni(25); pf17.setNum_lezioni(30); pf18.setNum_lezioni(30); pf19.setNum_lezioni(25); 
		pf20.setNum_lezioni(20); pf21.setNum_lezioni(15); pf22.setNum_lezioni(10); pf23.setNum_lezioni(5);  
		pf24.setNum_lezioni(5);  pf25.setNum_lezioni(10); pf26.setNum_lezioni(15); pf27.setNum_lezioni(20); 
		pf28.setNum_lezioni(25); pf29.setNum_lezioni(30); pf30.setNum_lezioni(30);
		
		pf0.setId_formatore(1);  pf1.setId_formatore(5);  pf2.setId_formatore(1);  pf3.setId_formatore(5);  
		pf4.setId_formatore(1);  pf5.setId_formatore(5);  pf6.setId_formatore(1);  pf7.setId_formatore(5);  
		pf8.setId_formatore(1);  pf9.setId_formatore(5);  pf10.setId_formatore(1); pf11.setId_formatore(5);  
		pf12.setId_formatore(1); pf13.setId_formatore(5); pf14.setId_formatore(1); pf15.setId_formatore(5); 
		pf16.setId_formatore(1); pf17.setId_formatore(5); pf18.setId_formatore(1); pf19.setId_formatore(5); 
		pf20.setId_formatore(1); pf21.setId_formatore(5); pf22.setId_formatore(1); pf23.setId_formatore(5);  
		pf24.setId_formatore(1); pf25.setId_formatore(5); pf26.setId_formatore(1); pf27.setId_formatore(5); 
		pf28.setId_formatore(1); pf29.setId_formatore(5); pf30.setId_formatore(1);
		
		pf0.setCategoria(3);  pf1.setCategoria(2);  pf2.setCategoria(1);  pf3.setCategoria(4);  pf4.setCategoria(4);
		pf5.setCategoria(3);  pf6.setCategoria(1);  pf7.setCategoria(2);  pf8.setCategoria(3);  pf9.setCategoria(2);
		pf10.setCategoria(1); pf11.setCategoria(2); pf12.setCategoria(4); pf13.setCategoria(4); pf14.setCategoria(2);
		pf15.setCategoria(2); pf16.setCategoria(5); pf17.setCategoria(3); pf18.setCategoria(2); pf19.setCategoria(2);
		pf20.setCategoria(1); pf21.setCategoria(3); pf22.setCategoria(2); pf23.setCategoria(4); pf24.setCategoria(3);
		pf25.setCategoria(4); pf26.setCategoria(1); pf27.setCategoria(1); pf28.setCategoria(1); pf29.setCategoria(4);
		pf30.setCategoria(4); 
		
		pfDao.doSave(pf0);  pfDao.doSave(pf1);  pfDao.doSave(pf2);  pfDao.doSave(pf3);  pfDao.doSave(pf4);  
		pfDao.doSave(pf5);  pfDao.doSave(pf6);  pfDao.doSave(pf7);  pfDao.doSave(pf8);  pfDao.doSave(pf9);  
		pfDao.doSave(pf10); pfDao.doSave(pf11); pfDao.doSave(pf12); pfDao.doSave(pf13); pfDao.doSave(pf14); 
		pfDao.doSave(pf15); pfDao.doSave(pf16); pfDao.doSave(pf17); pfDao.doSave(pf18); pfDao.doSave(pf19); 
		pfDao.doSave(pf20); pfDao.doSave(pf21); pfDao.doSave(pf22); pfDao.doSave(pf23); pfDao.doSave(pf24); 
		pfDao.doSave(pf25); pfDao.doSave(pf26); pfDao.doSave(pf27); pfDao.doSave(pf28); pfDao.doSave(pf29);
		pfDao.doSave(pf30); 
		
		pfDao.validation(0, 8);
		pfDao.validation(0, 18);
		pfDao.validation(0, 23);
		pfDao.validation(0, 33);
				
		
	}
	
	public void testInserimentoDisponibilita() throws SQLException {
		
		DisponibilitaEntity d0 = new DisponibilitaEntity();
		d0.setGiornoSettimana("lunedì");
		d0.setOrario("07:00");
		d0.setIdPercorso(4);
		d0.setStato(1);
		DisponibilitaEntity d1 = new DisponibilitaEntity();
		d1.setGiornoSettimana("martedì");
		d1.setOrario("07:00");
		d1.setIdPercorso(5);
		d1.setStato(1);
		DisponibilitaEntity d2 = new DisponibilitaEntity();
		d2.setGiornoSettimana("mercoledì");
		d2.setOrario("07:00");
		d2.setIdPercorso(6);
		d2.setStato(1);
		DisponibilitaEntity d3 = new DisponibilitaEntity();
		d3.setGiornoSettimana("giovedì");
		d3.setOrario("07:00");
		d3.setIdPercorso(7);
		d3.setStato(1);
		DisponibilitaEntity d4 = new DisponibilitaEntity();
		d4.setGiornoSettimana("venerdì");
		d4.setOrario("07:00");
		d4.setIdPercorso(8);
		d4.setStato(0);
		DisponibilitaEntity d5 = new DisponibilitaEntity();
		d5.setGiornoSettimana("lunedì");
		d5.setOrario("20:00");
		d5.setIdPercorso(9);
		d5.setStato(1);
		DisponibilitaEntity d6 = new DisponibilitaEntity();
		d6.setGiornoSettimana("martedì");
		d6.setOrario("20:00");
		d6.setIdPercorso(10);
		d6.setStato(0);
		DisponibilitaEntity d7 = new DisponibilitaEntity();
		d7.setGiornoSettimana("mercoledì");
		d7.setOrario("20:00");
		d7.setIdPercorso(11);
		d7.setStato(1);
		DisponibilitaEntity d8 = new DisponibilitaEntity();
		d8.setGiornoSettimana("giovedì");
		d8.setOrario("20:00");
		d8.setIdPercorso(12);
		d8.setStato(1);
		DisponibilitaEntity d9 = new DisponibilitaEntity();
		d9.setGiornoSettimana("venerdì");
		d9.setOrario("20:00");
		d9.setIdPercorso(13);
		d9.setStato(1);
		DisponibilitaEntity d10 = new DisponibilitaEntity();
		d10.setGiornoSettimana("lunedì");
		d10.setOrario("09:00");
		d10.setIdPercorso(14);
		d10.setStato(1);
		DisponibilitaEntity d11 = new DisponibilitaEntity();
		d11.setGiornoSettimana("martedì");
		d11.setOrario("09:00");
		d11.setIdPercorso(15);
		d11.setStato(1);
		DisponibilitaEntity d12 = new DisponibilitaEntity();
		d12.setGiornoSettimana("mercoledì");
		d12.setOrario("09:00");
		d12.setIdPercorso(16);
		d12.setStato(1);
		DisponibilitaEntity d13 = new DisponibilitaEntity();
		d13.setGiornoSettimana("giovedì");
		d13.setOrario("09:00");
		d13.setIdPercorso(17);
		d13.setStato(1);
		DisponibilitaEntity d14 = new DisponibilitaEntity();
		d14.setGiornoSettimana("venerdì");
		d14.setOrario("09:00");
		d14.setIdPercorso(18);
		d14.setStato(0);
		DisponibilitaEntity d15 = new DisponibilitaEntity();
		d15.setGiornoSettimana("lunedì");
		d15.setOrario("18:00");
		d15.setIdPercorso(19);
		d15.setStato(1);
		DisponibilitaEntity d16 = new DisponibilitaEntity();
		d16.setGiornoSettimana("martedì");
		d16.setOrario("18:00");
		d16.setIdPercorso(20);
		d16.setStato(1);
		DisponibilitaEntity d17 = new DisponibilitaEntity();
		d17.setGiornoSettimana("mercoledì");
		d17.setOrario("18:00");
		d17.setIdPercorso(21);
		d17.setStato(1);
		DisponibilitaEntity d18 = new DisponibilitaEntity();
		d18.setGiornoSettimana("giovedì");
		d18.setOrario("18:00");
		d18.setIdPercorso(22);
		d18.setStato(1);
		DisponibilitaEntity d19 = new DisponibilitaEntity();
		d19.setGiornoSettimana("venerdì");
		d19.setOrario("18:00");
		d19.setIdPercorso(23);
		d19.setStato(0);
		DisponibilitaEntity d20 = new DisponibilitaEntity();
		d20.setGiornoSettimana("lunedì");
		d20.setOrario("11:00");
		d20.setIdPercorso(24);
		d20.setStato(1);
		DisponibilitaEntity d21 = new DisponibilitaEntity();
		d21.setGiornoSettimana("martedì");
		d21.setOrario("11:00");
		d21.setIdPercorso(25);
		d21.setStato(1);
		DisponibilitaEntity d22 = new DisponibilitaEntity();
		d22.setGiornoSettimana("mercoledì");
		d22.setOrario("11:00");
		d22.setIdPercorso(26);
		d22.setStato(1);
		DisponibilitaEntity d23 = new DisponibilitaEntity();
		d23.setGiornoSettimana("giovedì");
		d23.setOrario("11:00");
		d23.setIdPercorso(27);
		d23.setStato(1);
		DisponibilitaEntity d24 = new DisponibilitaEntity();
		d24.setGiornoSettimana("venerdì");
		d24.setOrario("11:00");
		d24.setIdPercorso(28);
		d24.setStato(1);
		DisponibilitaEntity d25 = new DisponibilitaEntity();
		d25.setGiornoSettimana("lunedì");
		d25.setOrario("16:00");
		d25.setIdPercorso(29);
		d25.setStato(1);
		DisponibilitaEntity d26 = new DisponibilitaEntity();
		d26.setGiornoSettimana("martedì");
		d26.setOrario("16:00");
		d26.setIdPercorso(30);
		d26.setStato(1);
		DisponibilitaEntity d27 = new DisponibilitaEntity();
		d27.setGiornoSettimana("mercoledì");
		d27.setOrario("16:00");
		d27.setIdPercorso(31);
		d27.setStato(1);
		DisponibilitaEntity d28 = new DisponibilitaEntity();
		d28.setGiornoSettimana("giovedì");
		d28.setOrario("16:00");
		d28.setIdPercorso(32);
		d28.setStato(1);
		DisponibilitaEntity d29 = new DisponibilitaEntity();
		d29.setGiornoSettimana("venerdì");
		d29.setOrario("16:00");
		d29.setIdPercorso(33);
		d29.setStato(0);
		DisponibilitaEntity d30 = new DisponibilitaEntity();
		d30.setGiornoSettimana("lunedì");
		d30.setOrario("13:00");
		d30.setIdPercorso(34);
		d30.setStato(1);
		DisponibilitaEntity d31 = new DisponibilitaEntity();
		d31.setGiornoSettimana("martedì");
		d31.setOrario("13:00");
		d31.setIdPercorso(4);
		d31.setStato(1);
		DisponibilitaEntity d32 = new DisponibilitaEntity();
		d32.setGiornoSettimana("mercoledì");
		d32.setOrario("13:00");
		d32.setIdPercorso(5);
		d32.setStato(1);
		DisponibilitaEntity d33 = new DisponibilitaEntity();
		d33.setGiornoSettimana("giovedì");
		d33.setOrario("13:00");
		d33.setIdPercorso(6);
		d33.setStato(1);
		DisponibilitaEntity d34 = new DisponibilitaEntity();
		d34.setGiornoSettimana("venerdì");
		d34.setOrario("13:00");
		d34.setIdPercorso(7);
		d34.setStato(1);	
		DisponibilitaEntity d35 = new DisponibilitaEntity();
		d35.setGiornoSettimana("lunedì");
		d35.setOrario("14:00");
		d35.setIdPercorso(8);
		d35.setStato(0);
		DisponibilitaEntity d36 = new DisponibilitaEntity();
		d36.setGiornoSettimana("martedì");
		d36.setOrario("14:00");
		d36.setIdPercorso(9);
		d36.setStato(1);
		DisponibilitaEntity d37 = new DisponibilitaEntity();
		d37.setGiornoSettimana("mercoledì");
		d37.setOrario("14:00");
		d37.setIdPercorso(10);
		d37.setStato(1);
		DisponibilitaEntity d38 = new DisponibilitaEntity();
		d38.setGiornoSettimana("giovedì");
		d38.setOrario("14:00");
		d38.setIdPercorso(11);
		d38.setStato(1);
		DisponibilitaEntity d39 = new DisponibilitaEntity();
		d39.setGiornoSettimana("venerdì");
		d39.setOrario("14:00");
		d39.setIdPercorso(12);
		d39.setStato(1);
		DisponibilitaEntity d40 = new DisponibilitaEntity();
		d40.setGiornoSettimana("lunedì");
		d40.setOrario("15:00");
		d40.setIdPercorso(13);
		d40.setStato(1);
		DisponibilitaEntity d41 = new DisponibilitaEntity();
		d41.setGiornoSettimana("martedì");
		d41.setOrario("15:00");
		d41.setIdPercorso(14);
		d41.setStato(1);
		DisponibilitaEntity d42 = new DisponibilitaEntity();
		d42.setGiornoSettimana("mercoledì");
		d42.setOrario("15:00");
		d42.setIdPercorso(15);
		d42.setStato(1);
		DisponibilitaEntity d43 = new DisponibilitaEntity();
		d43.setGiornoSettimana("giovedì");
		d43.setOrario("15:00");
		d43.setIdPercorso(16);
		d43.setStato(1);
		DisponibilitaEntity d44 = new DisponibilitaEntity();
		d44.setGiornoSettimana("venerdì");
		d44.setOrario("15:00");
		d44.setIdPercorso(17);
		d44.setStato(1);
		DisponibilitaEntity d45 = new DisponibilitaEntity();
		d45.setGiornoSettimana("lunedì");
		d45.setOrario("12:00");
		d45.setIdPercorso(18);
		d45.setStato(0);
		DisponibilitaEntity d46 = new DisponibilitaEntity();
		d46.setGiornoSettimana("martedì");
		d46.setOrario("12:00");
		d46.setIdPercorso(19);
		d46.setStato(1);
		DisponibilitaEntity d47 = new DisponibilitaEntity();
		d47.setGiornoSettimana("mercoledì");
		d47.setOrario("12:00");
		d47.setIdPercorso(20);
		d47.setStato(0);
		DisponibilitaEntity d48 = new DisponibilitaEntity();
		d48.setGiornoSettimana("giovedì");
		d48.setOrario("12:00");
		d48.setIdPercorso(21);
		d48.setStato(1);
		DisponibilitaEntity d49 = new DisponibilitaEntity();
		d49.setGiornoSettimana("venerdì");
		d49.setOrario("12:00");
		d49.setIdPercorso(22);
		d49.setStato(1);
		DisponibilitaEntity d50 = new DisponibilitaEntity();
		d50.setGiornoSettimana("lunedì");
		d50.setOrario("17:00");
		d50.setIdPercorso(23);
		d50.setStato(0);
		DisponibilitaEntity d51 = new DisponibilitaEntity();
		d51.setGiornoSettimana("martedì");
		d51.setOrario("17:00");
		d51.setIdPercorso(24);
		d51.setStato(1);
		DisponibilitaEntity d52 = new DisponibilitaEntity();
		d52.setGiornoSettimana("mercoledì");
		d52.setOrario("17:00");
		d52.setIdPercorso(25);
		d52.setStato(1);
		DisponibilitaEntity d53 = new DisponibilitaEntity();
		d53.setGiornoSettimana("giovedì");
		d53.setOrario("17:00");
		d53.setIdPercorso(26);
		d53.setStato(1);
		DisponibilitaEntity d54 = new DisponibilitaEntity();
		d54.setGiornoSettimana("venerdì");
		d54.setOrario("17:00");
		d54.setIdPercorso(27);
		d54.setStato(1);
		DisponibilitaEntity d55 = new DisponibilitaEntity();
		d55.setGiornoSettimana("lunedì");
		d55.setOrario("10:00");
		d55.setIdPercorso(28);
		d55.setStato(1);
		DisponibilitaEntity d56 = new DisponibilitaEntity();
		d56.setGiornoSettimana("martedì");
		d56.setOrario("10:00");
		d56.setIdPercorso(29);
		d56.setStato(1);
		DisponibilitaEntity d57 = new DisponibilitaEntity();
		d57.setGiornoSettimana("mercoledì");
		d57.setOrario("10:00");
		d57.setIdPercorso(30);
		d57.setStato(1);
		DisponibilitaEntity d58 = new DisponibilitaEntity();
		d58.setGiornoSettimana("giovedì");
		d58.setOrario("10:00");
		d58.setIdPercorso(31);
		d58.setStato(1);
		DisponibilitaEntity d59 = new DisponibilitaEntity();
		d59.setGiornoSettimana("venerdì");
		d59.setOrario("10:00");
		d59.setIdPercorso(32);
		d59.setStato(1);
		DisponibilitaEntity d60 = new DisponibilitaEntity();
		d60.setGiornoSettimana("lunedì");
		d60.setOrario("19:00");
		d60.setIdPercorso(33);
		d60.setStato(0);
		DisponibilitaEntity d61 = new DisponibilitaEntity();
		d61.setGiornoSettimana("martedì");
		d61.setOrario("19:00");
		d61.setIdPercorso(34);
		d61.setStato(1);
		
		dDao.doSave(d0);  dDao.doSave(d1);  dDao.doSave(d2);  dDao.doSave(d3);  dDao.doSave(d4);  dDao.doSave(d5);
		dDao.doSave(d6);  dDao.doSave(d7);  dDao.doSave(d8);  dDao.doSave(d9);  dDao.doSave(d10); dDao.doSave(d11);
		dDao.doSave(d12); dDao.doSave(d13); dDao.doSave(d14); dDao.doSave(d15); dDao.doSave(d16); dDao.doSave(d17);
		dDao.doSave(d18); dDao.doSave(d19); dDao.doSave(d20); dDao.doSave(d21); dDao.doSave(d22); dDao.doSave(d23);
		dDao.doSave(d24); dDao.doSave(d25); dDao.doSave(d26); dDao.doSave(d27); dDao.doSave(d28); dDao.doSave(d29);
		
		dDao.doSave(d30); dDao.doSave(d31); dDao.doSave(d32); dDao.doSave(d33); dDao.doSave(d34); dDao.doSave(d35);
		dDao.doSave(d36); dDao.doSave(d37); dDao.doSave(d38); dDao.doSave(d39); dDao.doSave(d40); dDao.doSave(d41);
		dDao.doSave(d42); dDao.doSave(d43); dDao.doSave(d44); dDao.doSave(d45); dDao.doSave(d46); dDao.doSave(d47);
		dDao.doSave(d48); dDao.doSave(d49); dDao.doSave(d50); dDao.doSave(d51); dDao.doSave(d52); dDao.doSave(d53);
		dDao.doSave(d54); dDao.doSave(d55); dDao.doSave(d56); dDao.doSave(d57); dDao.doSave(d58); dDao.doSave(d59);
		dDao.doSave(d60); dDao.doSave(d61);
		
	}
	
	public void testInserimentoPreferenzaStudente() throws SQLException {
		
		PreferenzaStudenteEntity preferenza0 = new PreferenzaStudenteEntity();
		preferenza0.setStudente(5);    preferenza0.setDisponibilita("mercoledì");
		PreferenzaStudenteEntity preferenza1 = new PreferenzaStudenteEntity();
		preferenza1.setStudente(5);    preferenza1.setDisponibilita("venerdì");
		PreferenzaStudenteEntity preferenza2 = new PreferenzaStudenteEntity();
		preferenza2.setStudente(2);    preferenza2.setDisponibilita("giovedì");
		
		psDao.doSave(preferenza0); psDao.doSave(preferenza1); psDao.doSave(preferenza2); 
		
	}
	
	public void testInserimentoInteressi() throws SQLException {
		
		InteresseEntity interesse0 = new InteresseEntity();
		interesse0.setNome("3d (Informatica)");
		InteresseEntity interesse1 = new InteresseEntity();
		interesse1.setNome("Algebra (Matematica)");
		InteresseEntity interesse2 = new InteresseEntity();
		interesse2.setNome("C (Linguaggio)");
		InteresseEntity interesse3 = new InteresseEntity();
		interesse3.setNome("Algoritmi (Informatica)");
		InteresseEntity interesse4 = new InteresseEntity();
		interesse4.setNome("Analisi 1 (Matematica)");
		InteresseEntity interesse5 = new InteresseEntity();
		interesse5.setNome("HTML (Linguaggio)");
		InteresseEntity interesse6 = new InteresseEntity();
		interesse6.setNome("Grafica e interattività (Informatica)");
		InteresseEntity interesse7 = new InteresseEntity();
		interesse7.setNome("Geometria (Matematica)");
		InteresseEntity interesse8 = new InteresseEntity();
		interesse8.setNome("Java (Linguaggio)");
		
		interesseDao.doSave(interesse0); interesseDao.doSave(interesse1); interesseDao.doSave(interesse2);
		interesseDao.doSave(interesse3); interesseDao.doSave(interesse4); interesseDao.doSave(interesse5);
		interesseDao.doSave(interesse6); interesseDao.doSave(interesse7); interesseDao.doSave(interesse8);
	}
	
	public void testInserimentoInteressiStudenti() throws SQLException {
		
		InteresseStudenteEntity is0 = new InteresseStudenteEntity();
		is0.setStudente(5); is0.setInteresse(2);
		InteresseStudenteEntity is1 = new InteresseStudenteEntity();
		is1.setStudente(5); is1.setInteresse(3);
		InteresseStudenteEntity is2 = new InteresseStudenteEntity();
		is2.setStudente(5); is2.setInteresse(4);
		InteresseStudenteEntity is3 = new InteresseStudenteEntity();
		is3.setStudente(5); is3.setInteresse(10);
		InteresseStudenteEntity is4 = new InteresseStudenteEntity();
		is4.setStudente(5); is4.setInteresse(9);
		InteresseStudenteEntity is5 = new InteresseStudenteEntity();
		is5.setStudente(5); is5.setInteresse(8);
		InteresseStudenteEntity is6 = new InteresseStudenteEntity();
		is6.setStudente(2); is6.setInteresse(6);
		
		isDao.doSave(is0); isDao.doSave(is1); isDao.doSave(is2); isDao.doSave(is3);
		isDao.doSave(is4); isDao.doSave(is5); isDao.doSave(is6);
		
	}
	
	public void testInserimentoIscrizioni() throws ParseException, SQLException {
		
		IscrizioneEntity iscrizione0 = new IscrizioneEntity();
		iscrizione0.setStudente(5);
		iscrizione0.setPercorsoFormativo(10);
		iscrizione0.setGiorno("martedì");
		iscrizione0.setOrario("20:00");
		iscrizione0.setMetodoPagamento("mastercard");
		//set status a 0
		dDao.updateStatus(10,0);
		iscrizione0.setDataPagamento(Utils.toDate("05-05-2021"));
		
		IscrizioneEntity iscrizione1 = new IscrizioneEntity();
		iscrizione1.setStudente(5);
		iscrizione1.setPercorsoFormativo(20);
		iscrizione1.setGiorno("mercoledì");
		iscrizione1.setOrario("12:00");
		iscrizione1.setMetodoPagamento("visa");
		//set status  a 0
		dDao.updateStatus(20,0);
		iscrizione1.setDataPagamento(Utils.toDate("10-10-2021"));
		iscrizioneDao.doSave(iscrizione0);    iscrizioneDao.doSave(iscrizione1);
		
	}
	
}









